POST http://localhost:5555/client

Content-Type: application/json


 {

 "name": "Erika ",

"email": "erikaguimaraes@gmail.com"

}

####

GET http://localhost:5555/client

###
GET http://localhost:5555/client/1

###
PUT http://localhost:5555/client/1
Content-Type: application/json

{
"name": "Maria ",

"email": "maria@gmail.com"

}
###
DELETE http://localhost:5555/client/3